{
    'name': 'Productes per a Esdeveniments',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Plantilles i tiquets vinculats a esdeveniments',
    'depends': ['base','event', 'product', 'sale'],
    'post_load_hook': 'post_load_hook',
    'data': [
        'security/ir.model.access.csv',
        'views/event_views.xml',
        'views/product_views.xml',
        'views/menu_views.xml',
        'data/product_categories.xml',
        'data/product_templates.xml',
        'views/product_price_view.xml',
        'views/assign_event_category_wizard.xml',
        'views/menu.xml',
        'views/server_actions.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}